package org.tenbitworks.model;


import javax.persistence.*;
import javax.validation.constraints.NotNull;


@Entity
@Table(name = "member")
public class Member {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull
  private String email;

  private String status;
  
  @NotNull
  private String memberName;



  private String phoneNumber;

  private String paymentMethod;

  private String description;

  private String zipCode;

  // Public methods
  
  public Member() { }

  public Member(long id) { 
    this.id = id;
  }

  public Member(String memberName, String email ) {
    this.email = email;
    this.memberName = memberName;
  }

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getMemberName() {
    return memberName;
  }

  public void setMemberName(String memberName) {
    this.memberName = memberName;
  }

  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getZipCode() {
    return zipCode;
  }

  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  public String getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  @Override
  public String toString() {
    return "Member{" +
            "id=" + id +
            ", email='" + email + '\'' +
            ", status='" + status + '\'' +
            ", memberName='" + memberName + '\'' +
            '}';
  }
}